@local=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UxMDczMGVhYWY5ZGE0YTZhODBiNzkiLCJiaXoiOnRydWUsImlhdCI6MTY3NTg2MjM2NX0.MsaTGgbMUtjKgxvZfVclh0FG7Oo2N3MSbUzXwyJ7niQ
GET {{local}}/test
//Content-Type: application/json
###
//send new user (sign in) request
POST {{local}}/users
Content-Type: application/json

{
    "name": "aaaa",
    "password": "asdfgh",
    "email": "a@gmail.com",
    "biz": true
  }

###
//sent req for auth (log in)
POST {{local}}/auth
Content-Type: application/json

{
    "password": "asdfgh",
    "email": "asdf@gmail.com"
  }
###
GET {{local}}/users/me
x-auth-token:{{token}}


// send card req
###
GET {{local}}/card


###
POST {{local}}/card
x-auth-token:{{token}}
Content-Type: application/json

{
    "bizName": "basketball",
    "bizDescription":"basketball players plays basketball",
    "bizAddress": "USA ",
    "bizPhone": "0545454545",
    "bizImage":"https://cdn.pixabay.com/photo/2017/11/10/05/48/user-2935527_960_720.png" 
  }

###

